// Generated by CoffeeScript 1.9.2
(function() {
  var SerialPort, args, client, event, help, host, info, minimist, net, port, ref, resolve, serialport, sp, tty;

  net = require('net');

  minimist = require('minimist');

  serialport = require('serialport');

  SerialPort = serialport.SerialPort;

  ref = require('./utils'), info = ref.info, event = ref.event;

  help = function() {
    return console.log("usage: ttysocket [--help] --host SERVER_ADDR --port SERVER_PORT TTY_ADDR\n\noptional arguments:\n  --help                    show this help message and exit\n  --host SERVER_ADDR        server address\n  --port SERVER_PORT        server port");
  };

  if (process.argv.length < 3) {
    return help();
  }

  args = minimist(process.argv.slice(2));

  if (args.help != null) {
    return help();
  }

  port = args.port || 14580;

  host = args.host || 'hangzhou.aprs2.net';

  tty = args._[0];

  if (tty == null) {
    return help();
  }


  /* SerialPort Readline Loop */

  sp = new SerialPort(tty, {
    parser: serialport.parsers.readline("\n")
  });


  /* Use stdin */


  /* sp = process.stdin */


  /* Socket Connection */

  client = net.createConnection(port, host, function() {
    return event("Connected to " + host + ":" + port);
  });

  client.on('data', function(data) {
    data = data.toString();

    /* Filter ping data */
    if (data.indexOf('ping') !== data.length - 6) {
      return info(data);
    }
  });

  client.on('end', function() {
    return event("Disconnected to " + host + ":" + port);
  });


  /* Write data to remote server */

  sp.on('data', function(line) {
    line = line.toString();
    client.write(resolve(line));
    return event("Response has written to socket.");
  });


  /* Resolve messages which needs to implement */

  resolve = function(line) {
    return line + "\n";
  };

}).call(this);
