// Generated by CoffeeScript 1.9.2
(function() {
  var hostname, net, port, readline, resolve, rl;

  readline = require('readline');

  net = require('net');

  port = process.env['port'] || 34123;

  hostname = process.env['hostname'] || '127.0.0.1';


  /* Readline Loop */

  rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });


  /* Socket Server */

  net.createServer(function(socket) {
    return rl.on('line', function(line) {
      socket.write(resolve(line));
      return console.log("Response for '" + line + "' has written to socket");
    });
  }).listen(port, hostname, function() {
    return console.log("Server listening on " + hostname + ":" + port);
  });


  /* Resolve messages which needs to implement */

  resolve = function(line) {
    return line + "\n";
  };

}).call(this);
